#!/bin/bash

DEST_DIR="public"
PAGES_DIR="pages"
RESOURCES_DIR="resources"
STYLES_DIR="public/css/"
STYLE_SHEET="styles.css"
TEMPLATE_DIR="templates"

rm -r $DEST_DIR/*
cp -r $RESOURCES_DIR/* $DEST_DIR/

asciidoctor --trace \
    -a stylesdir=../$STYLES_DIR -a stylesheet=$STYLE_SHEET \
    -a stylehref="/css/$STYLE_SHEET" \
    --destination-dir $DEST_DIR \
    --source-dir $PAGES_DIR \
    --template-dir $TEMPLATE_DIR \
    -- $PAGES_DIR/**/*.adoc

if [[ "$OSTYPE" =~ "darwin" ]]; then
    nginx -s reload
else
    service nginx reload
fi
